### ISSUE TITLE
Visual interaction with repository view of files

### ISSUE THREAD

**Issue by jwalkerbg** [dominch/redmine_highlightjs#8] opened 2015-09-12 09:14 UTC
Hello,

There is some visual interaction between redmine_highlightjs 1.0.1 with the file views from repositories. 

Environment:
  Redmine version                2.6.6.stable
  Ruby version                   1.9.3-p194 (2012-04-20) [i386-mingw32]
  Rails version                  3.2.22
  Environment                    production
  Database adapter               Mysql2
SCM:
  Subversion                     1.8.13
  Git                            1.9.5
  Filesystem  
Redmine plugins:
  clipboard_image_paste          1.10
  projects_tree_view             0.0.8
  redmine_checklists             3.1.1
  redmine_code_review            0.6.4
  redmine_didyoumean             1.2.0
  redmine_highlightjs            1.0.1
  redmine_issue_detailed_tabs_time 0.1.0
  redmine_issue_templates        0.0.9
  redmine_latex_mathjax          0.1.0
  redmine_local_avatars          0.1.1
  redmine_pastebin               0.2.0
  redmine_plugin_views_revisions 0.0.1
  redmine_silencer               0.4.0
  redmine_theme_changer          0.1.0
  redmine_user_issues            0.0.2
  redmine_wiki_gchart_formula    0.0.5
  redmine_xls_export             0.2.1
  redmine_youtube                0.0.1
  sidebar_hide                   0.0.6
  wiking                         1.0.0b

I experienced this with C files. When redmine_highlightjs is active the distance between the lines is about twice the normal spacing. Also, the formatting is lost.

Here is normal spacing and formatting
https://www.dropbox.com/s/3xuhwnu4snxvipn/normal_spacing.PNG?dl=0
and here is doubled spacing
https://www.dropbox.com/s/83ou5vn0t290436/extended_spacing.PNG?dl=0

,

**Comment by dominch** [comment] 2015-09-12 13:31
hello, 
Thanks for detailed raport! This is duplicate of issue #3 

I'm working now on this issue and it should be fixed in few days, 
The problem with view file is that You don't have one big `<pre><code>` but table with those tags at each line. This won't be highlighted corectly by lib and highlighting bigger files takes some time. And there is a problem because at this point I can't reproduce all functionality of that view (line numbers!). I'm testing few things and hope to come up with some solution. 

You can checkout `dev` branch - this is not yet optimized version without line numbers, better than nothing but I'm still not satisfied. 
I'm closing this issue because it's #3, let's switch there :)

**Closed as completed by dominch** 2015-09-12 13:31 UTC
Labels: duplicate
