### ISSUE TITLE
Not work in repository

### ISSUE THREAD

**Issue by Krakozaber** [dominch/redmine_highlightjs#7] opened 2015-09-10 06:36 UTC
Not work in git repository

**Comment by dominch** [comment] 2015-09-10 08:39
I just checked on four redmine instances and it works great, 
You need to provide more information about Your instance (version, installed plugins, etc.)

**Comment by Krakozaber** [comment] 2015-09-10 09:55
Redmine 3.0.3

plugins: redmine_xapian, redmine_checklist, redmine_ldap_sync

Install:
copy redmine_highlightjs -> ./redmine/plugins
/var/lib/gems/1.9.1/bin/bundle install --without development test && rake1.9.1 redmine:plugins:migrate RAILS_ENV=production

..../apache2 restart

In firebug I can see that highlight.js and css loaded. (Firefox 40)

**Comment by dominch** [comment] 2015-09-10 13:32
I just tried redmine stable 3.0.x (3.0.4) with Your plugins, and it worked without any problems, the only difference is ruby (2.1.5) but this should not be an issue 
Check out javascript console, are there any errors? 
Check content of loaded CSS and JS file - are they ok? (meaning content format)  
Review any example `<pre><code>...</pre></code>` in firebug - it should receive hljs class, is it? 
Are You using non-default theme?

**Comment by Krakozaber** [comment] 2015-09-11 03:37
use Alternate in Redmine and Default in plugin config

**Comment by dominch** [comment] 2015-09-11 09:27
Still works on my test instance, Alternate theme + default scheme in plugin config. 
Please answer questions above. I can't reproduce Your issue and I don't have any clue what may be wrong on Your side. 

Make sure You are using latest version from github (1.0.1) .

BTW: what makes You think it's not working? Can You attach any screenshot?

**Comment by Krakozaber** [comment] 2015-09-11 10:42
Update Redmine to 3.1.0

![redmine](https://cloud.githubusercontent.com/assets/2918147/9813047/4c4e5088-5893-11e5-9a8c-382716da6eff.png)

**Comment by dominch** [comment] 2015-09-11 11:04
Ok, now it's clear - plugin is not loaded here yet, but those views are not `<pre><code>..` blocks that You can insert. In fact it's duplicate of #3 
I assumed that it's not working on whole page, now I know that You meant source view only. I'm closing this issue as duplicate of previous ticket, I hope to take a look at this i few days :) 

Thanks for Your raport :)

**Closed as completed by dominch** 2015-09-11 11:04 UTC
Labels: duplicate

**Comment by Krakozaber** [comment] 2015-09-11 11:06
It`s git repository connected to Redmine

**Comment by dominch** [comment] 2015-09-11 11:13
Yep, I know now, this wasn't cleat at topic start :) 
I'll take a look at this and try to fix that, it should not be very difficult. :) 
I'll let You know in #3

**Comment by Krakozaber** [comment] 2015-09-11 11:16
Thanks
